# Generated by Django 5.1.7 on 2025-04-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_market_store_products2_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DiscountProduct',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
