# Generated by Django 5.1.7 on 2025-06-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_store_shoppinglistitem_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='completed',
        ),
    ]
