# Generated by Django 5.1.7 on 2025-09-16 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_subcategory_products2_subcategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppinglistitem',
            unique_together={('shopping_list', 'product')},
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products2')),
            ],
            options={
                'db_table': 'product_history2',
            },
        ),
    ]
